// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe8_3Mpj51KyoLP6ggkuMR1iYd_iVJhUk',
    appId: '1:850376552890:web:b12760f81f0847fd43ad83',
    messagingSenderId: '850376552890',
    projectId: 'backendflutter-f9b1c',
    authDomain: 'backendflutter-f9b1c.firebaseapp.com',
    databaseURL: 'https://backendflutter-f9b1c-default-rtdb.firebaseio.com',
    storageBucket: 'backendflutter-f9b1c.firebasestorage.app',
    measurementId: 'G-1CK4231NSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuWFIf5fRmmneewftzEmUnkoRLQYGoUgw',
    appId: '1:850376552890:android:20226b7608bb59a243ad83',
    messagingSenderId: '850376552890',
    projectId: 'backendflutter-f9b1c',
    databaseURL: 'https://backendflutter-f9b1c-default-rtdb.firebaseio.com',
    storageBucket: 'backendflutter-f9b1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC39NcOFBFhVZWd-Fq59WyhAHXT0aparmI',
    appId: '1:850376552890:ios:e49e1b6c571efc0a43ad83',
    messagingSenderId: '850376552890',
    projectId: 'backendflutter-f9b1c',
    databaseURL: 'https://backendflutter-f9b1c-default-rtdb.firebaseio.com',
    storageBucket: 'backendflutter-f9b1c.firebasestorage.app',
    iosBundleId: 'com.example.lojaLivros',
  );
}
